SELECT /*+ ORDERED NO_MERGE(SES) */
  SES.SID ,
  SES.EVENT ,
  SQL2.OLD_HASH_VALUE,
  SQL2.SQL_ID,
  SES.LAST_CALL_ET LAST_CALL_ET ,
  SES.MODULE MODULE ,
  SQL.PIECE PIECE ,
  SQL.SQL_TEXT SQL_TEXT
FROM
(select /*+ ORDERED */
 NVL(w.EVENT,'long active session') EVENT,
 s.SID,
 s.LAST_CALL_ET,
 s.MODULE,
 s.SQL_ADDRESS,
 s.SQL_HASH_VALUE
from v$session s,v$session_wait w
where s.sid = w.sid
and s.STATUS='ACTIVE'
and s.USERNAME is not NULL
and (s.LAST_CALL_ET > 10 or w.EVENT like 'enq%' or w.EVENT like 'latch%'))
SES,
  V$SQLTEXT SQL,
  V$SQL     SQL2
WHERE SES.SQL_ADDRESS=SQL.ADDRESS
  AND SES.SQL_HASH_VALUE=SQL.HASH_VALUE
  AND SQL.HASH_VALUE = SQL2.HASH_VALUE
  AND SQL.SQL_ID = SQL2.SQL_ID
ORDER BY
  SES.SID,
  LAST_CALL_ET DESC ,
  OLD_HASH_VALUE,
  PIECE
;
