SELECT /*+ ORDERED */
  'enqueue wait' EVENT , 
  A.HASH_VALUE HASH_VALUE , 
  S.LAST_CALL_ET LAST_CALL_ET , 
  S.MODULE MODULE , 
  A.PIECE PIECE , 
  A.SQL_TEXT SQL_TEXT 
FROM 
  V$SESSION S , 
  V$SQLTEXT A 
WHERE 
  S.SQL_ADDRESS=A.ADDRESS 
  AND S.SQL_HASH_VALUE=A.HASH_VALUE 
  AND S.SID 
  IN ( SELECT SID FROM V$SESSION_WAIT WHERE EVENT = 'enqueue' ) 
  AND S.USERNAME IS NOT NULL 
UNION 
SELECT /*+ ORDERED */
  'latch free wait' EVENT , 
  A.HASH_VALUE HASH_VALUE , 
  S.LAST_CALL_ET LAST_CALL_ET , 
  S.MODULE MODULE , 
  A.PIECE PIECE , 
  A.SQL_TEXT SQL_TEXT 
FROM 
  V$SESSION S , 
  V$SQLTEXT A 
WHERE 
  S.SQL_ADDRESS=A.ADDRESS 
  AND S.SQL_HASH_VALUE=A.HASH_VALUE 
  AND S.SID 
  IN ( SELECT SID FROM V$SESSION_WAIT WHERE EVENT = 'latch free' ) 
  AND S.USERNAME IS NOT NULL 
ORDER BY 
  LAST_CALL_ET 
  DESC , 
  HASH_VALUE , 
  PIECE
;
